### PR TITLE
Fixes 0.37.4

### PR DESCRIPTION
**Pull request by hallvard**
Thanks for contributing.

- [x ] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Pulled and built v. 0.37.4 and had two issues:

- ColumnTest.testMap2 failed, since the second argument to map must set the size.
- To create correct shaded jar for jsplot, the unescape library must be included

BTW, another test failed, too, TemplateUtilsTest's test of custom template location. The Page component uses a static PebbleEngine that is initialised too early to pick up custom location.

## Testing

One fix was in a test, the other was tested manually, by using the shaded jar in an Eclipse plugin.

### CODE REVIEW

**Comment by benmccann** [comment]
I don't think the tests failed on the continuous build or my machine, so this is weird

In any case, you'll need to rebase this PR as it currently can't be merged due to conflicts

**Comment by hallvard** [comment]
`git clone` into a new directory and `mvn test` gave
`ColumnTest.testMap2:285 » IndexOutOfBounds Index (0) is greater than or equal ...`

The UI says "This branch has no conflicts with the base branch"???

**Comment by benmccann** [comment]
Here's what I see

Screenshot from 2020-02-17 08-09-31

**Comment by hallvard** [comment]
Weird:

Screenshot 2020-02-17 at 17 13 08

**Comment by hallvard** [comment]
Anyway, I'm happy if you apply my two very small changes manually: https://github.com/jtablesaw/tablesaw/pull/760/files

**Comment by benmccann** [comment]
Done

**Pull request closed without merging**
