### PR TITLE
Add JSON reader support

### PR DESCRIPTION
**Pull request by benmccann**
Thanks for contributing.

- [X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Described in https://github.com/jtablesaw/tablesaw/issues/374. The tests demonstrate the functionality well

Created base class `ReadOptions` for `CsvReadOptions`  to decouple cell parsing from CSV reading
Refactored out `ColumnTypeDetector` from `CsvReader` so that it could be used in reading html and json

## Testing

Added unit tests for new JsonReader functionality

### CODE REVIEW

**Comment by benmccann** [comment]
@lwhite1 I pushed some more updates to this. I'm pretty happy with it, but thought I'd give you a chance to give it a look since it's a decent sized change. Let me know if you're busy and want me to just go ahead without a review

**Comment by benmccann** [comment]
@lwhite1 is this something you want to review? if so, do you think you'll have a chance this weekend?

**Comment by lwhite1** [comment]
This looks great, Ben. Sorry for the delay.

**Comment by benmccann** [comment]
No, worries. You didn't take too long. I'm just being a bit impatient cause I'm eager to use this in a project of mine :-)

**Pull request merged**
