### PR TITLE
Code Optimization

### PR DESCRIPTION
**Pull request by divyeshjagatiya**
## Description
Convert from array of object to string by (Collectors.joining)

### CODE REVIEW

**Comment by lwhite1** [comment]
How much time does it save?  Or is this a different kind of optimization?

**Comment by benmccann** [comment]
I'm guessing it's optimization in terms of fewer lines of code. But I think this is going to be slower.

If we care about performance, then this:

    "'" + String.valueOf(d) + "'"

Would be better written as:

    new StringBuilder("'").append(String.valueOf(d)).append("'").toString()

**Comment by divyeshjagatiya** [comment]
you r right

**Comment by lwhite1** [comment]
First, thanks very much. 

This code is **much** cleaner than mine, and normally I would be all for it. In this case, though, I'd rather not add the overhead. Even if you make the change that Ben suggests, you'll be making a new StringBuilder for each element in the array, because map gets called on every element.

**Comment by divyeshjagatiya** [comment]
i will try to make batter than this as per your suggestion.
Thanks,

**Comment by lwhite1** [comment]
Closing unless/until we get a better, fast implementation.

**Pull request closed without merging**
