### PR TITLE
Generalize DataFrameJoiner.java

### PR DESCRIPTION
**Pull request by gregorco**
Thanks for contributing.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Change the DataFrameJoiner.java to replace references to CategoricalColumn type with the more general Column type.  This is a step toward generalizing the joining of tables on any column type.  The joining implementation is still limited to certain column types, but this begins the change toward not requiring columns to be categorical columns. 

## Testing

Added junit tests to expect Exceptions that were already happening in expected conditions, like in joinInternal and fullOuter methods which throw IllegalArgumentException if column is not an integral, string, or data-like type.

### CODE REVIEW

**Comment by lwhite1** [comment]
Hi @gregorco,

Is this ready for merge? I think I misunderstood where we were and already merged much of this of changes when they're ready. Then you can go back to branching from master for any further contributions. (which are much appreciated)

Does that make sense?

**Comment by gregorco** [comment]
Hi @lwhite1 ,

For my very first PR I had worked on a local branch, then merged it to my master, and submitted my master for the PR.  Later I was reminded by @benmccann that it would probably be better for PR's to be submitted through a PR-specific branch so that my master branch can stay in sync with upstream/master so that I could possibly work on two PRs at the same time without having the master branch be a bottleneck between PRs.  

For this PR I first updated my master from upstream/master, then created a branch, generalize-joiner, from my master to make the changes to just two files.  I'm confused by the top of this page where it lists all of my previous commits starting from my first PR.  I thought that this PR would identify only the two commits that I've made to this branch before I submitted the PR.  I expect that you'd only need to review the two files that I changed in my last two commits for this PR.   

What should I have done so that this PR would only show it having two commits?

**Comment by benmccann** [comment]
I think your repo got messed up because you were working on master. I would recommend deleting it and creating a new fork of this repo. Then as long as you only put changes on your repo's master by syncing from this repo you should not have issues.

**Comment by lwhite1** [comment]
(insert shrug icon here.)

My guess is that when you branched from master, the remote merge of your code into master hadn't happened yet, so your master was ahead by all these commits, and when you branched from it your new branch was ahead also.

Don't sweat it. We'll get these merged and you can start clean if you'd like to make any additional contributions.

**Comment by gregorco** [comment]
Sounds good.  So with a newly forked repo, for PR's I should create a PR-specific branch off of my master, eventually submit that branch for the PR, then update my master once that PR-specific branch has been accepted/merged into the upstream/master.  That way I never merge my branch back into my master and my master stays sync'd with upstream?  Does that sound correct?

**Pull request merged**
