### PR TITLE
To support annotation in plot.ly javascript.

### PR DESCRIPTION
**Pull request by xcjusuih**
Thanks for contributing.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

I add basic support for annotation in plot.ly as issue #615 want. It can support most of apis in annotation. 

## Testing

Did you add a unit test?

I write 2 tests for 2 conditions in [guideline of annotation](https://plotly.com/javascript/text-and-annotations) and both of them have past.

### CODE REVIEW

**Comment by lwhite1** [comment]
Can you provide a couple examples (in the test folder tech.tablesaw.examples) that show this working with other plots?

**Comment by lwhite1** [comment]
> Can you provide a couple examples (in the test folder tech.tablesaw.examples) that show this working with other plots?

Hi @xcjusuih, Do you think you might be able to provide some examples in the near future or should we do a release without these changes?

**Comment by xcjusuih** [comment]
I think perhaps in next week as I am busy with final exam.

**Comment by lwhite1** [comment]
that's fine. Good luck with your exams.

**Comment by lwhite1** [comment]
i guess we can go without the example code as there are tests.

**Pull request merged**
