### PR TITLE
simple implementation of selectRows method

### PR DESCRIPTION
**Pull request by artichaud1**
Based on logic in dropRows method.
Issue #185.
(Haven't ran any tests as I'm still learning how to deal with java projects...but the code is straightforward).

### CODE REVIEW

**Comment by benmccann** [comment]
@artichaud1 thanks for this! I'm curious what your use case is if you don't mind sharing how you intend to use this new method

@lwhite1 thoughts?  I'm not sure it makes sense to expose `IntArrayList` to users as `dropRows` is currently doing. It seems like it should be an internal implementation detail that we're using `fastutil` and it would be better to expose an interface taking `Collection<Integer>` instead

**Comment by artichaud1** [comment]
A few examples that come to mind:
- easily split a table into chunks for a home-made and quick map/reduce type of job.
- for time series data, I might want to train on top part of the table and test on bottom part.
- I might want for some odd reason to see what the table looks like in the middle instead of the head of the tail. Or maybe I just know the exact indices of the rows I'm interested in.

**Comment by lwhite1** [comment]
I think collection<Integer> is better for an API method, although it sounds
like most of your use cases would be better served by specifying a range or
RangeSet

**Comment by benmccann** [comment]
Thanks for reviewing @lwhite1. I had the same thought that a range would be better as well.

Thanks for suggesting this improvement @artichaud1. I changed the existing drop methods to take a range and Collection instead. I added the corresponding selectRow methods as well

**Comment by artichaud1** [comment]
Very cool !
Btw: I probably did it wrong, but it wasn't my suggestion, I took the easiest issue I could find.
Question: if I want to test the new methods in beaker, what would be the simplest way ? (I assume they are not already reflected in mvn jars ?)

**Comment by benmccann** [comment]
The approach you took made a lot of sense given the existing code.

If you run `mvn install` then if will install to your local Maven repository and you should be able to then reference it from BeakerX or another project. It can be pretty tricky to get it to work though. It can often take me awhile to figure out how to get it to work and I know Java pretty well. You can give it a shot, but it might just be easier to wait awhile for the next release

**Pull request closed without merging**
