### PR TITLE
Updates the Column.mapInto javadoc and adds two new Column.map methods

### PR DESCRIPTION
**Pull request by emilianbold**
Thanks for contributing.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

This fixed issue #704 by updating the `Column.mapInto` javadoc.

It also adds two new `Column.map` methods which offer a way to append data to a newly created column. The output column is easily created/provided via a `Supplier` or `Function`.

## Testing

Yes.

### CODE REVIEW

**Comment by emilianbold** [comment]
Ooh, interestingly `NumericColumn` has a separate `mapInto` that does `append`!

**Comment by benmccann** [comment]
Let's remove the `NumericColumn` version then so it inherits the main one

I don't know that we need the new methods because it should be pretty easy to use the existing methods to accomplish the same thing. E.g. the user could just create the column with an initial size instead of empty and use `mapTo`

**Comment by emilianbold** [comment]
To me something like `StringColumn s = d.map(String::valueOf, StringColumn::create)` looks in line with other stream APIs, eg. [`Stream.toArray(int[]::new)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#toArray(java.util.function.IntFunction) )

Right now `d.mapInto(String::valueOf, StringColumn.create(d.name(), d.size()))` works but I dislike the manual setting of the size (and, partially, the setting of the name).

I'll remove the `NumericColumn` method too.

**Comment by benmccann** [comment]
Ok. Makes sense. At least for the one taking a creator. What's the use case for the one taking a supplier?

**Comment by emilianbold** [comment]
Actually, the `NumericColumn.mapInto` takes a `DoubleFunction` so we can't remove it. We could add the same logic (`set` instead of `append`) but it might break existing code...

**Comment by emilianbold** [comment]
> What's the use case for the one taking a supplier?

Good point, if we have the creator it's enough.

**Comment by benmccann** [comment]
The new creator method let's you do `StringColumn s = d.map(String::valueOf, StringColumn::create`.  But actually, don't we already have a method that lets you do `StringColumn s = d.map(String::valueOf)`?

**Comment by emilianbold** [comment]
> But actually, don't we already have a method that lets you do `StringColumn s = d.map(String::valueOf)`?

Not as far as I can tell. If `d` is a `DoubleColumn` then `map` will create another `DoubleColumn`. You cannot change the column type with a `map`, only `mapInto`.

**Pull request merged**
