### PR TITLE
Use existing charset when available for creating reader

### PR DESCRIPTION
**Pull request by benmccann**
Thanks for contributing.

- [X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Review by lwhite1 — APPROVED** [review]
So the idea is to use an InputStreamReader that has been instantiated with the desired Charset?  This looks good to me. It does leave open the question of how to manage this for a File data source, since file doesn't have a charset.  Any thoughts on that?

**Comment by lwhite1** [comment]
Actually, I just realized that the UnivocityParser has parse methods for InputStream and File that take a Charset argument. Is this bypassing that mechanism?

**Comment by benmccann** [comment]
You can use an `InputStreamReader` for a `File` as well. I didn't look at where we instantiate the `UnivocityParser`, but the place that was giving us trouble in the bug report was the column type detection method

**Comment by lwhite1** [comment]
Ok. Let's give it a try

**Pull request merged**
