### PR TITLE
Add convenience methods to convert to double arrays for easier usage with Smile

### PR DESCRIPTION
**Pull request by benmccann**
- [X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

This makes using Tablesaw with Smile a bit smoother as described in https://github.com/jtablesaw/tablesaw/issues/280#issuecomment-403702698.

Converting to double arrays and matrices is super common. E.g.:
```
moneyball.numberColumn("RD").asDoubleArray()
moneyball.copy().retainColumns("W").asMatrix()
```

This PR provides a much simpler API for this common operation:
```
moneyball.asDoubleArray("RD")
moneyball.asMatrix("W")
```

### CODE REVIEW

**Comment by lwhite1** [comment]
I think asDoubleArray() belongs on the column since you're only converting the column. You're not doing anything with the table other than retrieving the column, which is a common operation any tablesaw user would know. I would rather not add it to the relation/table API. 

AsMatrix is definitely better in the sense that it is a multi-column operation, if not an actual table operation like sort. The benefit is that it's easier to find than the DoubleArrays class, but it's not necessarily _easy_ to find. There are over 150 methods on Relation/Table.  

You don't have to copy and retain, you can use any of these: 

- DoubleArrays.to2DArray(moneyball.columns());
- DoubleArrays.to2DArray(moneyball.columns("W", "L"));
- DoubleArrays.to2DArray(moneyball.numberColumns());
etc.

These are properly multi-column operations. 

I'm sure the uses for this functionality expands beyond the (vanishingly small intersection of Smile/Tablesaw users) so it's worth spending some time on, but I suspect there are Smile functions that take int[] or int[][], or other similar things. I've seen some visualization libraries (JavaFX for example), that like float[] instead of double[].  

All things considered, I'm not convinced that there isn't a better way to organize this functionality. Maybe by renaming the DoubleArrays class (and methods) and getting it out of utils (api or a new converter/conversions package might not be so bad). 

tech.tablesaw.api.TableConverter? 

What do you think?

**Comment by lwhite1** [comment]
An example of an additional, possibly useful, conversion is to ND4J (N-Dimensional Arrays for Java) format. https://nd4j.org/. 

They're billing it as like numpy for java. It seems likely that future ML libraries will support it.

**Comment by lwhite1** [comment]
> Today I do have to copy and retain, because the columns(String...) method doesn't exist. 

The PR moves it from table to relation, which is a clear improvement and should be done. 

> Regarding ND4J, you create a row/column vector from a double[] or a 2d NDArray from a double[][], so these would help there as well.

or an int[] or float[], but sure. 

> I have another idea. What if we make the API look like:
```
moneyball.as().matrix("W")

```
I like it. Should the matrix method be typed, rather than always producing double[][]?

**Comment by benmccann** [comment]
Ok, I've updated the PR to have `as().floatMatrix()`, `as().doubleMatrix()`, `as().intMatrix()`

**Pull request merged**
