### PR TITLE
fix for #395 It's impossible to parse CSV file with more than 512 columns

### PR DESCRIPTION
**Pull request by Ebalaitung**
[X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

CSVParser columns size changed from 512 to Integer.MAX_VALUE

## Testing

no need for unit tests in this case

### CODE REVIEW

**Comment by benmccann** [comment]
Looks good to me. I'll let Larry review before merging

**Comment by benmccann** [comment]
Actually, I just saw his comment on the issue that he approves of this, so I'll go ahead and merge

**Comment by lwhite1** [comment]
@Ebalaitung @benmccann  - is this what broke the build?  Seems to be the last commit made. A test is running out of memory in CSV parsing.

**Comment by benmccann** [comment]
Yes. @Ebalaitung I've reverted this commit. If you'd like to send a PR that adds an option we can merge that

**Comment by Ebalaitung** [comment]
Yrp, got it, will add this setting to parsrr6

**Pull request merged**
