### PR TITLE
Saw enhancements

### PR DESCRIPTION
**Pull request by lwhite1**
Thanks for contributing.

- [X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

What was changed
Restructured the SAW IO code, adding various performance enhancements, comments, tests and some functional improvements. 

### Functional Improvements
- Added the ability to load only a subset of the columns in the table. This can be handy for large tables
- Added metadata about the table, that can be queried without loading the table, including
-- rowcount, columncount, columnNames
-- table shape()
-- table structure()
-- Added the ability to turn off compression 
-- Added a placeholder for including encrypting the files in a possible future release (so that change will be backward 
compatible with files stored in the current version)

### Performance Improvements
Saw is now roughly as fast as Apache Arrow, able to read 15 million row table in about 3 seconds. The table tested was a saw version of a 2.7 GB CSV file from NYC Taxi Commission (Yellow Cab Data - January 2010). It takes nearly 2 minutes to load the same file as a CSV

## Testing

Did you add a unit test?
Yes.

### CODE REVIEW

**Comment by lwhite1** [comment]
This is a draft so no need to review yet. I want to undo some things or at least move them to another PR

**Comment by benmccann** [comment]
I'll probably skip reviewing this one since I've never used the saw reader, so don't wait on me

**Comment by lwhite1** [comment]
That's fine. It's a lot of work for nothing if you're not interested.

**Comment by lwhite1** [comment]
Note: the bug identified by SonarCloud isn't a bug.

**Pull request merged**
